// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qhvsEFajx3fwI_QbGF0NXn_PGFztrY0',
    appId: '1:434163240515:web:723e1fea69a8359ab44ef6',
    messagingSenderId: '434163240515',
    projectId: 'tezda-3e7cd',
    authDomain: 'tezda-3e7cd.firebaseapp.com',
    storageBucket: 'tezda-3e7cd.firebasestorage.app',
    measurementId: 'G-YY1P4MW34F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_l-mrpR-WldB2IUTV-aMcYm-vtZRlqU',
    appId: '1:434163240515:android:c0a18654c9d7ccd1b44ef6',
    messagingSenderId: '434163240515',
    projectId: 'tezda-3e7cd',
    storageBucket: 'tezda-3e7cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARK_ptZEQNpVMf51vmyLzHxB-cgdoXqSs',
    appId: '1:434163240515:ios:dc93ffb6168c307cb44ef6',
    messagingSenderId: '434163240515',
    projectId: 'tezda-3e7cd',
    storageBucket: 'tezda-3e7cd.firebasestorage.app',
    iosBundleId: 'com.example.tezda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARK_ptZEQNpVMf51vmyLzHxB-cgdoXqSs',
    appId: '1:434163240515:ios:dc93ffb6168c307cb44ef6',
    messagingSenderId: '434163240515',
    projectId: 'tezda-3e7cd',
    storageBucket: 'tezda-3e7cd.firebasestorage.app',
    iosBundleId: 'com.example.tezda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qhvsEFajx3fwI_QbGF0NXn_PGFztrY0',
    appId: '1:434163240515:web:dc00c48c3aa4a78eb44ef6',
    messagingSenderId: '434163240515',
    projectId: 'tezda-3e7cd',
    authDomain: 'tezda-3e7cd.firebaseapp.com',
    storageBucket: 'tezda-3e7cd.firebasestorage.app',
    measurementId: 'G-59DY7QHFPE',
  );
}
